# Generated by Django 4.2.4 on 2023-08-28 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=20)),
                ("author_id", models.CharField(max_length=20)),
                ("num_of_fans", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_stitle", models.CharField(max_length=100)),
                ("pub_date", models.DateField()),
                ("num_read", models.IntegerField()),
                ("news_content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newspage.author",
                    ),
                ),
            ],
        ),
    ]
