# Generated by Django 4.2.4 on 2023-08-30 10:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("newspage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="author",
            managers=[
                ("authormanager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="news",
            managers=[
                ("newsmanager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name="news",
            old_name="new_stitle",
            new_name="news_title",
        ),
        migrations.RemoveField(
            model_name="author",
            name="author_id",
        ),
        migrations.RemoveField(
            model_name="author",
            name="num_of_fans",
        ),
    ]
