# Generated by Django 4.2.4 on 2023-09-02 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newspage", "0003_segname_alter_author_managers_alter_news_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="segcontent",
            name="ranking",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="segcontent",
            name="its_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="newspage.news"
            ),
        ),
        migrations.AlterField(
            model_name="segcontent",
            name="its_seg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="newspage.segname"
            ),
        ),
    ]
