# Generated by Django 4.2.4 on 2023-09-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspage", "0004_segcontent_ranking_alter_segcontent_its_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="author_link",
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
    ]
