# Generated by Django 4.2.4 on 2023-09-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newspage", "0007_comment_comment_time_news_news_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segcontent",
            name="ranking",
        ),
    ]
