# Generated by Django 4.2.4 on 2023-09-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newspage", "0010_alter_news_news_content_alter_news_news_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="its_author",
        ),
    ]
