# Generated by Django 4.2.4 on 2023-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspage", "0011_remove_comment_its_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_link",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="news_title",
            field=models.CharField(max_length=100),
        ),
    ]
