# Generated by Django 4.2.4 on 2023-09-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspage", "0012_news_news_link_alter_news_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="news_link",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="news",
            name="news_title",
            field=models.CharField(max_length=40),
        ),
    ]
